version: '3'
services:
  docs-build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../../:/linux
    environment:
      # workaround for binfmt_misc support in containers
      - SPHINX_DITAA_CMD=jexec
      - SPHINX_DITAA_ARG=/usr/bin/ditaa
